export default interface Transaction {
    "account_id": string,
    "amount": number,
    "iso_currency_code": string | undefined | null,
    "unofficial_currency_code": string | undefined | null,
    "category": string[] | undefined | null,
    "category_id": string | undefined | null,
    "date": string,
    "authorized_date": string | undefined | null,
    "location": {
      "address": string | undefined | null,
      "city": string | undefined | null,
      "region": string | undefined | null,
      "postal_code": string | undefined | null,
      "country": string | undefined | null,
      "lat": number | undefined | null,
      "lon": number | undefined | null,
      "store_number": string | undefined | null,
    },
    "name": string,
    "merchant_name": string,
    "payment_meta": {
      "by_order_of": string | undefined | null,
      "payee": string | undefined | null,
      "payer": string | undefined | null,
      "payment_method": string | undefined | null,
      "payment_processor": string | undefined | null,
      "ppd_id": string | undefined | null,
      "reason": string | undefined | null,
      "reference_number": string | undefined | null,
    },
    "payment_channel": string | undefined | null,
    "pending": boolean,
    "pending_transaction_id": string | undefined | null,
    "account_owner": string | undefined | null,
    "transaction_id": string,
    "transaction_code": string | undefined | null,
    "transaction_type": string
  }